* Project idea

Measure the performance of io_uring with the latest performance
improvements compared to DPDK. There are already papers that that
compared io_uring to DPDK, but io_uring moves fast and there have been
new mechanisms introduced to make networking faster.

* Plan for the report

** Introduction

Introduce the different networking stacks, explain why they have
different performance characteristics and the tradeoffs in usability,
hardware support and integration with the OS.

** Motivation

Say that io_uring has been gaining new APIs to make networking faster
and that the benchmarks need to be updated to those new APIs to see if
DPDK is still the obvious choice when writing high performance
networking applications.

** Background

*** DPDK

Explain how DPDK works.

*** io_uring

Explain how io_uring works.

**** Fixed files
**** Buffer ring
**** Zero-copy transmission
**** Zero-copy reception

** Benchmarks

*** Code
*** Environment

The hardware and software used to run the benchmarks, and how the
packets were received or transmitted outside of the host being
benchmarked.

** Results

*** Transmission
*** Reception

** Conclusion

* Plan for myself
